services:
  - type: web
    name: celetem-securite
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
